#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/majialun/Documents/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/majialun/Documents/code/github/flutter-p2p-engine/example"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/majialun/Documents/code/github/flutter-p2p-engine/example/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "FLUTTER_BUILD_NAME=1.6.0"
export "FLUTTER_BUILD_NUMBER=4"
export "DART_DEFINES=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ=="
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/majialun/Documents/code/github/flutter-p2p-engine/example/.dart_tool/package_config.json"
